project:
  type: book
  output-dir: docs

book:
  title: "Data Science for Political Science"
  date: "September 2024"
  chapters:
    - index.qmd
    - intro.qmd
    - 02-Description.qmd
    - 03-CausalityI.qmd
    - 04-Visualization.qmd
    - 05-Causalityii.qmd
    - 06-Loops.qmd
    - 07-Prediction.qmd
    - 08-Regression.qmd
    - 09-Fairness.qmd
    - 10-Uncertainty.qmd
    - 11-TextasData.qmd
    - 12-Maps.qmd
    - 13-ChooseYourOwnAdventure.qmd
  page-navigation: true
  sidebar:
    style: docked
    background: light
    foreground: darkred

format:
  html:
    theme: yeti
    toc-title: Section Contents
    toc: true
    toc-location: left
    toc-depth: 4
    linkcolor: red
  pdf:
    toc-title: Section Contents
    toc: true
    toc-location: left
    toc-depth: 4
    linkcolor: red
  


editor: visual

